version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: base

  magento:
     depends_on:
       - db
     image: alexcheng/magento2:latest
     ports:
       - "8002:80"
     restart: always
     environment:
       MAGENTO_DB_HOST: db:3306
       MAGENTO_DB_USER: user
       MAGENTO_DB_PASSWORD: 123456
       MAGENTO_DB_NAME: base

  tomcat:
     depends_on:
       - db
     image: bitnami/tomcat
     volumes:
       - ./test.war:/usr/local/tomcat/webapps/test.war
     ports:
       - '8082:8080'

volumes:
  db_data: {}


