version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8000:80"
    networks:
      - app-network

  magento:
    depends_on:
      - db
    image: alexcheng/magento2:latest
    container_name: magento
    restart: always
    ports:
      - "8002:80"
    networks:
      - app-network

  tomcat:
    depends_on:
      - db
    image: bitnami/tomcat
    container_name: tomcat
    restart: always
    volumes:
      - ./test.war:/usr/local/tomcat/webapps/test.war
    ports:
      - "8082:8080"
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

volumes:
  db_data: {}

networks:
  app-network:
    driver: bridge